Moving tilt to use helm instead of static yaml
ori-edge/k8s_gateway pull request #74
Opened 2022-01-14 11:21 UTC by networkop

TODO:
-[]: remove old `test/kubernetes.yaml`
-[]: check if ingress-nginx can be changed to helm
-[]: pin versions on all helm charts

2022-01-21 09:55 UTC, networkop commented
@Kaezon can you give a quick overview? I wanted to merge this before I forget all about this PR.

2022-01-21 17:48 UTC, Kaezon commented
Yes, sorry. I let this fall off my plate. I'll go back over it now.

2022-01-21 18:33 UTC, Kaezon requested changes
The only thing I see is that one note I made on the VirtualServer CR.
Pretty sure you can just point it to one of the services defined in `test.yaml` and call it good.

2022-01-21 18:35 UTC, Kaezon commented on test/nginxinc-kubernetes-ingress/resources.yaml
> -  name: nginx-test-a
Also, I thought this note was visible when I made it almost a week ago, but I guess it only shows up when I complete the review?

2022-01-22 09:02 UTC, networkop commented on test/nginxinc-kubernetes-ingress/resources.yaml
> -  name: nginx-test-a
yep, I see. I'll probably factor out that deployment+service part and make to make them common for all Ingress/VR resources.

2022-01-23 16:11 UTC, merged